# Site settings
title: Try{Finally}
email: d9n.coding@gmail.com
description: A coding blog about game development with programming tutorials.
baseurl: "/tryfinally"
url: "http://d9n.github.io"
permalink: pretty

# Defaults
defaults:
  -
    scope:
      path: "series/understanding_gradle"
    values:
      series_title: "Understanding Gradle"

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
 - jekyll-coffeescript

include:
  - ".nojekyll" # Tell github pages we build jekyll ourselves
exclude:
  - "README.md"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "scripts"
  - "npm-debug.log"
