# Site settings
title: Try { Finally }
email: d9n.coding@gmail.com
description: >
  <b>Carefully crafted coding tutorials</b>
  <p>
  Learn, discuss, and enjoy!
baseurl: "/tutorials"
url: "http://d9n.github.io"
#twitter_username: 
github_username:  d9n 

# Build settings
markdown: kramdown
sass:
  style: compressed

include:
  - ".nojekyll" # Tell github pages we build jekyll ourselves
exclude:
  - "README.md"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "scripts"
