# Site settings
title: Try{Finally}
email: d9n.coding@gmail.com
description: >
  <b>Carefully crafted coding tutorials</b>
  <p>
  Learn, discuss, and enjoy!
baseurl: "/tryfinally"
url: "http://d9n.github.io"
github_username: d9n

# Defaults
defaults:
  -
    scope:
      path: "series/kotlin"
    values:
      series_title: "Making an Android Game with Kotlin and LibGdx"
      github_repo: "kotlin_keep"
      github_branch: "master"

# Build settings
markdown: kramdown
sass:
  style: compressed

include:
  - ".nojekyll" # Tell github pages we build jekyll ourselves
exclude:
  - "README.md"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "scripts"
